return {
--   {
--   'saghen/blink.cmp',
--   lazy = false,
--   dependencies = 'rafamadriz/friendly-snippets',
--   version = 'v0.3.1',
--   opts = {
--     keymap = {
--       accept = "<Tab>",
--       select_prev = { "<S-CR>", "<Up>", "<C-p>" },
--       select_next = { "<CR>", "<Down>", "<C-n>" },
--     },
--     windows = { documentation = { auto_show = true } },
--     highlight = { use_nvim_cmp_as_default = true },
--     nerd_font_variant = 'mono',
--
--     -- experimental auto-brackets support
--     accept = { auto_brackets = { enabled = true } },
--
--     -- experimental signature help support
--     trigger = { signature_help = { enabled = true } },
--   },
-- },
}
